[context.production]
  VITE_ORGANIZATION_ID = "barcasportsmcy01fvu"
  VITE_ENVIRONMENT = "dev"
  VITE_ACCESS_TOKEN = "xx0d59029f-ae1d-4725-a689-b312a0aeebca"
  VITE_SEARCH_URL = "https://sports-dev.barca.group/search"
  VITE_LISTING_1_URL = "https://sports-dev.barca.group/plp/accessories/surf-accessories"
  VITE_LISTING_2_URL = "https://sports-dev.barca.group/plp/clothing/pants"
  VITE_LISTING_3_URL = "https://sports-dev.barca.group/plp/accessories/towels"
  VITE_RECS_1_URL = "https://sports-dev.barca.group/recs1"
  VITE_RECS_2_URL = "https://sports-dev.barca.group/recs2"

  # Jamboree 1_EN
  VITE_1_EN_TRACKING_ID = "jamboree_1"
  VITE_1_EN_LANGUAGE = "en"
  VITE_1_EN_COUNTRY = "US"
  VITE_1_EN_CURRENCY = "USD"
  VITE_1_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_1_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_1_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 1_FR
  VITE_1_FR_TRACKING_ID = "jamboree_1"
  VITE_1_FR_LANGUAGE = "fr"
  VITE_1_FR_COUNTRY = "FR"
  VITE_1_FR_CURRENCY = "EUR"
  VITE_1_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_1_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_1_FR_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 2_EN
  VITE_2_EN_TRACKING_ID = "jamboree_2"
  VITE_2_EN_LANGUAGE = "en"
  VITE_2_EN_COUNTRY = "US"
  VITE_2_EN_CURRENCY = "USD"
  VITE_2_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_2_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_2_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 2_FR
  VITE_2_FR_TRACKING_ID = "jamboree_2"
  VITE_2_FR_LANGUAGE = "fr"
  VITE_2_FR_COUNTRY = "FR"
  VITE_2_FR_CURRENCY = "EUR"
  VITE_2_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_2_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_2_FR_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 3_EN
  VITE_3_EN_TRACKING_ID = "jamboree_3"
  VITE_3_EN_LANGUAGE = "en"
  VITE_3_EN_COUNTRY = "US"
  VITE_3_EN_CURRENCY = "USD"
  VITE_3_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_3_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_3_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 3_FR
  VITE_3_FR_TRACKING_ID = "jamboree_3"
  VITE_3_FR_LANGUAGE = "fr"
  VITE_3_FR_COUNTRY = "FR"
  VITE_3_FR_CURRENCY = "EUR"
  VITE_3_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_3_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_3_FR_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 4_EN
  VITE_4_EN_TRACKING_ID = "jamboree_4"
  VITE_4_EN_LANGUAGE = "en"
  VITE_4_EN_COUNTRY = "US"
  VITE_4_EN_CURRENCY = "USD"
  VITE_4_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_4_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_4_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 4_FR
  VITE_4_FR_TRACKING_ID = "jamboree_4"
  VITE_4_FR_LANGUAGE = "fr"
  VITE_4_FR_COUNTRY = "FR"
  VITE_4_FR_CURRENCY = "EUR"
  VITE_4_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_4_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_4_FR_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 5_EN
  VITE_5_EN_TRACKING_ID = "jamboree_5"
  VITE_5_EN_LANGUAGE = "en"
  VITE_5_EN_COUNTRY = "US"
  VITE_5_EN_CURRENCY = "USD"
  VITE_5_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_5_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_5_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 5_FR
  VITE_5_FR_TRACKING_ID = "jamboree_5"
  VITE_5_FR_LANGUAGE = "fr"
  VITE_5_FR_COUNTRY = "FR"
  VITE_5_FR_CURRENCY = "EUR"
  VITE_5_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_5_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_5_FR_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 6_EN
  VITE_6_EN_TRACKING_ID = "jamboree_6"
  VITE_6_EN_LANGUAGE = "en"
  VITE_6_EN_COUNTRY = "US"
  VITE_6_EN_CURRENCY = "USD"
  VITE_6_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_6_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_6_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 6_FR
  VITE_6_FR_TRACKING_ID = "jamboree_6"
  VITE_6_FR_LANGUAGE = "fr"
  VITE_6_FR_COUNTRY = "FR"
  VITE_6_FR_CURRENCY = "EUR"
  VITE_6_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_6_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_6_FR_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 7_EN
  VITE_7_EN_TRACKING_ID = "jamboree_7"
  VITE_7_EN_LANGUAGE = "en"
  VITE_7_EN_COUNTRY = "US"
  VITE_7_EN_CURRENCY = "USD"
  VITE_7_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_7_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_7_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 7_FR
  VITE_7_FR_TRACKING_ID = "jamboree_7"
  VITE_7_FR_LANGUAGE = "fr"
  VITE_7_FR_COUNTRY = "FR"
  VITE_7_FR_CURRENCY = "EUR"
  VITE_7_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_7_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_7_FR_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 8_EN
  VITE_8_EN_TRACKING_ID = "jamboree_8"
  VITE_8_EN_LANGUAGE = "en"
  VITE_8_EN_COUNTRY = "US"
  VITE_8_EN_CURRENCY = "USD"
  VITE_8_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_8_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_8_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 8_FR
  VITE_8_FR_TRACKING_ID = "jamboree_8"
  VITE_8_FR_LANGUAGE = "fr"
  VITE_8_FR_COUNTRY = "FR"
  VITE_8_FR_CURRENCY = "EUR"
  VITE_8_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_8_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_8_FR_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 9_EN
  VITE_9_EN_TRACKING_ID = "jamboree_9"
  VITE_9_EN_LANGUAGE = "en"
  VITE_9_EN_COUNTRY = "US"
  VITE_9_EN_CURRENCY = "USD"
  VITE_9_EN_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_9_EN_SLOT_ID_POPULAR_VIEWED = ""
  VITE_9_EN_SLOT_ID_CART_RECOMMENDATIONS = ""

  # Jamboree 9_FR
  VITE_9_FR_TRACKING_ID = "jamboree_9"
  VITE_9_FR_LANGUAGE = "fr"
  VITE_9_FR_COUNTRY = "FR"
  VITE_9_FR_CURRENCY = "EUR"
  VITE_9_FR_SLOT_ID_POPULAR_BOUGHT = ""
  VITE_9_FR_SLOT_ID_POPULAR_VIEWED = ""
  VITE_9_FR_SLOT_ID_CART_RECOMMENDATIONS = ""
